local_costmap:
  global_frame:       odom
  robot_base_frame:   base_footprint
  # update_frequency:   20.0        # Hz
  # publish_frequency:  10.0        # Hz
  # transform_tolerance: 1.0        # s

  rolling_window: true
  width:   5.0                    # metres
  height:  5.0
  resolution: 0.05                # metres/cell

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # # -- Local-only tweaks --------------------------------------
  # obstacle_layer:
  #   obstacle_range:  2.5          # may tighten for higher fps
  #   raytrace_range:  3.0
