obstacle_range: 2.0
raytrace_range: 2.5

# footprint: [[0.125, 0.125], [0.125, -0.125], [-0.125, -0.125], [-0.125, 0.125]]
footprint: [[0.15, 0.15], [0.15, -0.15], [-0.15, -0.15], [-0.15, 0.15]]
# robot_radius: 0.2

inflation_radius: 0.75
cost_scaling_factor: 10.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
robot_base_frame: base_footprint
