obstacle_range: 0.5
raytrace_range: 3.5

# footprint: [[0.125, 0.125], [0.125, -0.125], [-0.125, -0.125], [-0.125, 0.125]]
robot_radius: 0.2

inflation_radius: 0.5
cost_scaling_factor: 1.0

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
robot_base_frame: base_footprint
