local_costmap:
  global_frame:       odom        # non-drifting frame for velocity control
  robot_base_frame:   base_footprint
  update_frequency:   5.0         # Hz
  publish_frequency:  2.0         # Hz
  transform_tolerance: 0.5        # s

  rolling_window: true
  width:   4.0                    # metres
  height:  4.0
  resolution: 0.05                # metres/cell

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # -- Local-only tweaks --------------------------------------
  obstacle_layer:
    obstacle_range:  2.5          # may tighten for higher fps
    raytrace_range:  3.0
