# ─── Robot footprint ──────────────────────────────────────────
footprint:  [[ 0.25,  0.25],
             [ 0.25, -0.25],
             [-0.25, -0.25],
             [-0.25,  0.25]]
# max_obstacle_height: 0.60   # uncomment if you must filter tall hits

# ─── Obstacle layer (2-D LiDAR) ───────────────────────────────
obstacle_layer:
  enabled:              true
  combination_method:   1            # keep highest cost when merging
  track_unknown_space:  true         # planner avoids grey cells
  obstacle_range:       2.5
  raytrace_range:       3.0

  observation_sources:  scan
  scan:
    data_type:          LaserScan
    topic:              scan
    marking:            true
    clearing:           true
    # min_obstacle_height: 0.25      # ignore floor echoes
    # max_obstacle_height: 0.35      # ignore anything above base

# ─── Inflation layer ──────────────────────────────────────────
inflation_layer:
  enabled:              true
  inflation_radius:     0.55
  cost_scaling_factor:  10.0

# ─── Static layer ─────────────────────────────────────────────
static_layer:
  enabled:              true
  subscribe_to_updates: true         # accept /map incrementals
