# ─── Robot footprint ──────────────────────────────────────────
footprint:  [[ 0.26,  0.26],
             [ 0.26, -0.26],
             [-0.26, -0.26],
             [-0.26,  0.26]]

# ─── Frequency ──────────────────────────────────────────
update_frequency:   5.0        # Hz
publish_frequency:  1.0        # Hz
transform_tolerance: 1.0       # s

# ─── Obstacle layer (2-D LiDAR) ───────────────────────────────
obstacle_layer:
  enabled:              true
  combination_method:   1            # keep highest cost when merging
  track_unknown_space:  true         # planner avoids grey cells
  obstacle_range:       2.5
  raytrace_range:       3.0

  observation_sources:  scan
  scan:
    sensor_frame:       base_scan
    data_type:          LaserScan
    topic:              /scan
    marking:            true
    clearing:           true

# ─── Inflation layer ──────────────────────────────────────────
inflation_layer:
  enabled:              true
  inflation_radius:     1.5
  cost_scaling_factor:  2.0

# ─── Static layer ─────────────────────────────────────────────
static_layer:
  enabled:              true
  subscribe_to_updates: true         # accept /map incrementals
