# no obstacle_layer here — we’ll replace that with height_map_layer below
obstacle_range: 2.5
raytrace_range: 3.0

robot_radius: 0.25

plugins:
  - {name: static_layer,      type: "costmap_2d::StaticLayer"}
  - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
  - {name: height_map_layer,  type: "costmap_2d::OccupancyGridLayer"}   # ← use StaticLayer

height_map_layer:
  map_topic: /height_map
  subscribe_to_updates: true
  track_unknown_space: true
  use_maximum: false
  lethal_cost_threshold: 99         # default, ok
  unknown_cost_value: -1
  trinary_costmap: false            # <-- CRITICAL: don't collapse to 0/100/-1
  track_unknown_space: true

