global_costmap:
  global_frame:       map
  robot_base_frame:   base_footprint
  update_frequency:   1.0         # Hz
  publish_frequency:  0.5         # Hz
  transform_tolerance: 0.5        # s

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}   # remove if not wanted
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # -- Per-layer overrides (rarely needed here) ---------------
  #static_layer:
  #  map_topic: map         # default, shown only for clarity
