GlobalPlanner:
  use_quadratic: true           # Use quadratic cost scaling for smoother paths
  use_dijkstra: true           # Use A* for faster and smoother path planning
  allow_unknown: false          # Allow planning in unknown space
  planner_costmap_width: 10.0   # Ensure wide enough costmap for smoother planning
  planner_costmap_height: 10.0
  default_tolerance: 0.5