map_update_interval: 1.0  # Faster map update
maxUrange: 3.05
sigma: 0.01  # 🔥 Reduce noise model (clean up noise)
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.01  # 🔥 Reduce laser noise
ogain: 3.0
lskip: 0
minimumScore: 30  # 🔥 Lower minimum score to accept noisy scans
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 0.3  # ✅ Faster updates for moving robot
angularUpdate: 0.2
temporalUpdate: 0.5
resampleThreshold: 0.5
particles: 150  # ✅ Increase particles for robustness
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
