DWAPlannerROS:

# Robot Configuration Parameters
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_th: 0.0
  max_vel_trans: 0.1
  min_vel_trans: 0.05
  max_vel_x: 0.2
  min_vel_x: -0.2
  max_vel_y: 0.2
  min_vel_y: -0.2
  max_vel_theta: 0.1
  min_vel_theta: -0.1

# Goal Tolerance Parametes
  yaw_goal_tolerance: 3.14
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 6.0
  sim_granularity: 0.05
  vx_samples: 30
  vy_samples: 30
  vth_samples: 0
  controller_frequency: 5.0

# Trajectory Scoring Parameters
  path_distance_bias: 40.0
  goal_distance_bias: 8.0
  occdist_scale: 0.025
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 10.0
  max_scaling_factor: 0.2
  publish_cost_grid_pc: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.15

# Global Plan Parameters
  prune_plan: true



  holonomic_robot: true