DWAPlannerROS:

# Robot Configuration Parameters
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_th: 1.0
  max_vel_trans: 1.0
  min_vel_trans: 1
  max_vel_x: 1.0
  min_vel_x: -1.0
  max_vel_y: 0.0
  min_vel_y: -0.0
  max_vel_theta: 0.5
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.2  # Reduce hesitation in rotation
# Goal Tolerance Parametes
  yaw_goal_tolerance: 3.14
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

# Forward Simulation Parameters
  sim_time: 5.0
  sim_granularity: 0.025
  vx_samples: 10
  vy_samples: 0
  vth_samples: 25
  controller_frequency: 20.0

# Trajectory Scoring Parameters
  path_distance_bias: 64.0
  goal_distance_bias: 32.0
  occdist_scale: 0.1
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid_pc: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Global Plan Parameters
  prune_plan: true
