controller_frequency:        20.0
planner_patience:            5.0
controller_patience:         15.0
conservative_reset_dist:     3.0
recovery_behavior_enabled:   true
clearing_rotation_allowed:   false
shutdown_costmaps:           false
oscillation_timeout:         10.0
oscillation_distance:        0.5
planner_frequency:           0.0
max_planning_retries:        -1

# only use scan_flat for *clearing*, never *marking*
observation_sources: scan_flat
scan_flat:
  data_type:  LaserScan
  topic:      /scan_flat
  marking:    false
  clearing:   true
