GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.1 
  visualize_potential: true # disable if not debugging
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false  
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 5.0 
  publish_potential: true  # disable if not debugging 
  orientation_mode: 0
  orientation_window_size: 1
  outline_map: true