# a = ascending | d = descending

ramps:

  - id: "ramp1_a"
    from: "1"
    to:   "2"
    entry_pose: [ -12, 2, 0.0 ]
    exit_pose:  [ 0, 0.2, 0.0 ]
    blind_len:  0.5
    orientation: 90.0
  - id: "ramp1_d"
    from: "2"
    to:   "1"
    entry_pose: [ 0, 0.2, 0.0 ]
    exit_pose:  [ -12, 2, 0.0 ]
    blind_len:  0.5
    orientation: -90.0
  # - id: "ramp1_a"
  #   from: "1"
  #   to:   "2"
  #   entry_pose: [ 2.50, 0.00, 0.0 ]
  #   exit_pose:  [ -2.50, -5.00, 0.0 ]
  #   blind_len:  5.2
  #   orientation: 0.0
  # - id: "ramp1_d"
  #   from: "2"
  #   to:   "1"
  #   entry_pose: [ -2.50, -5.00, 180 ]
  #   exit_pose:  [ 2.50, 0.00, 180 ]
  #   blind_len:  5.2
  #   orientation: 180.0

  # - id: "ramp2_a"
  #   from: "2"
  #   to:   "3"
  #   entry_pose: [ -2.50, 5.00, 180 ] 
  #   exit_pose:  [ 2.50, 0.00, 180 ]
  #   blind_len:  5.2
  #   orientation: 180.0
  # - id: "ramp2_d"
  #   from: "3"
  #   to:   "2"
  #   entry_pose: [ 2.50, 0.00, 0.0 ]
  #   exit_pose:  [ -2.50, 5.00, 0.0 ]
  #   blind_len:  5.2
  #   orientation: 0.0

  # - id: "ramp3_a"
  #   from: "1"
  #   to:   "3"
  #   entry_pose: [ 0.00, 2.50, 0.0 ]
  #   exit_pose:  [ 0.00, -2.50, 0.0 ]
  #   blind_len:  5.5
  #   orientation: 90.0
  # - id: "ramp3_d"
  #   from: "3"
  #   to:   "1"
  #   entry_pose: [ 0.00, -2.50, -90 ]
  #   exit_pose:  [ 0.00, 2.50, -90 ]
  #   blind_len:  5.5
  #   orientation: -90.0